remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: true
  other: true
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - "Next.js"
  - "Frontend Developer"
  - "React Developer"
  - "Web Developer"
  - "Fullstack Developer"

locations:
  - "Ahmedabad, Gujarat, India"
  - "Germany"
  - "USA"
  - "Hof"
  - "Mumbai, Maharashtra, India"
  - "Saarbr√ºcken"
  - "Pune, Maharashtra, India"
  - "Bayreuth"
  - "Hyderabad, Telangana, India"
  - "Berlin"
  - "London"
  - "Paris"
  - "Michigan"
  - "Bangalore, Karnataka, India"
  - "New York"
  - "Tokyo"
  - "Chennai, Tamil Nadu, India"
  - "Remote"

apply_once_at_company: true

distance: 100

company_blacklist:

title_blacklist:
  - "golang"
  - "go"
  - "Java"
  - "Angular"
  - "Angular Js"
  - "Ruby"
  - "Python"
  - "Dot Net"
  - ".Net"
  - "C#"
  - "C Sharp"
  - "Asp.Net"
  - "Asp Net"
  - "Asp.Net Core"
  - "Asp Net Core"
  - "Asp.Net Mvc"
  - "Asp Net Mvc"
  - "Asp.Net Web Api"
  - "Asp Net Web Api"

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: gemini
llm_model: 'gemini-1.5-flash-latest'
llm_api_url: 'http://127.0.0.1:11434/'
